# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: machine.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='machine.proto',
  package='machine',
  serialized_pb='\n\rmachine.proto\x12\x07machine\"\xe3\x01\n\rMachineStatus\x12\r\n\x05temps\x18\x01 \x03(\x02\x12\x11\n\tfanSpeeds\x18\x02 \x03(\x02\x12\x16\n\x0etimeIntoRoasts\x18\x03 \x03(\x02\x12\x31\n\x05state\x18\x04 \x01(\x0e\x32\x1c.machine.MachineStatus.State:\x04IDLE\"e\n\x05State\x12\x08\n\x04IDLE\x10\x00\x12\x0b\n\x07HEATING\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0c\n\x08ROASTING\x10\x03\x12\x08\n\x04\x42USY\x10\x04\x12\x0b\n\x07\x43OOLING\x10\x05\x12\x08\n\x04OPEN\x10\x06\x12\x0b\n\x07PROBLEM\x10\t')



_MACHINESTATUS_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='machine.MachineStatus.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEATING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROASTING', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COOLING', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROBLEM', index=7, number=9,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=153,
  serialized_end=254,
)


_MACHINESTATUS = _descriptor.Descriptor(
  name='MachineStatus',
  full_name='machine.MachineStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temps', full_name='machine.MachineStatus.temps', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fanSpeeds', full_name='machine.MachineStatus.fanSpeeds', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeIntoRoasts', full_name='machine.MachineStatus.timeIntoRoasts', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='machine.MachineStatus.state', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MACHINESTATUS_STATE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=254,
)

_MACHINESTATUS.fields_by_name['state'].enum_type = _MACHINESTATUS_STATE
_MACHINESTATUS_STATE.containing_type = _MACHINESTATUS;
DESCRIPTOR.message_types_by_name['MachineStatus'] = _MACHINESTATUS

class MachineStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MACHINESTATUS

  # @@protoc_insertion_point(class_scope:machine.MachineStatus)


# @@protoc_insertion_point(module_scope)
